# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mxi_Q5dhnU-JUsogVk9BRfiR6NiR_VQp
"""

from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

SCOPES = ["https://www.googleapis.com/auth/calendar.readonly"]
TZ = ZoneInfo("America/Argentina/Buenos_Aires")

def main():
    creds = Credentials.from_authorized_user_file("token.json", SCOPES)

    if creds.expired and creds.refresh_token:
        creds.refresh(Request())
        with open("token.json", "w", encoding="utf-8") as f:
            f.write(creds.to_json())

    service = build("calendar", "v3", credentials=creds)

    calendars = service.calendarList().list().execute().get("items", [])
    print("Calendarios accesibles:")
    for cal in calendars:
        print("-", cal.get("summary"), "|", cal.get("id"))

    now = datetime.now(TZ)
    start = now.replace(hour=0, minute=0, second=0, microsecond=0)
    end = start + timedelta(days=1)

    print("\nEventos de hoy:\n")
    for cal in calendars:
        cal_id = cal["id"]
        cal_name = cal.get("summary", cal_id)
        try:
            events = service.events().list(
                calendarId=cal_id,
                timeMin=start.isoformat(),
                timeMax=end.isoformat(),
                singleEvents=True,
                orderBy="startTime",
            ).execute().get("items", [])

            if events:
                print(f"[{cal_name}]")
                for ev in events:
                    summary = ev.get("summary", "(Sin título)")
                    start_ev = ev["start"].get("dateTime") or ev["start"].get("date")
                    print(" ", start_ev, "-", summary)
                print()
        except Exception as e:
            print(f"Error en {cal_name}: {e}")

if __name__ == "__main__":
    main()