# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mxi_Q5dhnU-JUsogVk9BRfiR6NiR_VQp
"""

import os
import sys
import logging
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

import requests
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from googleapiclient.discovery import build

SCOPES = ["https://www.googleapis.com/auth/calendar.readonly"]
TZ = ZoneInfo("America/Argentina/Buenos_Aires")

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
log = logging.getLogger(__name__)

DAYS_ES = {
    "Monday": "lunes",
    "Tuesday": "martes",
    "Wednesday": "miércoles",
    "Thursday": "jueves",
    "Friday": "viernes",
    "Saturday": "sábado",
    "Sunday": "domingo",
}
MONTHS_ES = {
    1: "enero", 2: "febrero", 3: "marzo", 4: "abril", 5: "mayo", 6: "junio",
    7: "julio", 8: "agosto", 9: "septiembre", 10: "octubre", 11: "noviembre", 12: "diciembre"
}

def load_credentials():
    creds = Credentials.from_authorized_user_file("token.json", SCOPES)

    if creds.expired and creds.refresh_token:
        log.info("Token expirado. Refrescando.")
        creds.refresh(Request())
        with open("token.json", "w", encoding="utf-8") as f:
            f.write(creds.to_json())

    return creds

def get_calendar_service():
    return build("calendar", "v3", credentials=load_credentials())

def get_events(service, time_min: datetime, time_max: datetime) -> list:
    calendars = service.calendarList().list().execute().get("items", [])
    all_events = []

    for cal in calendars:
        cal_id = cal["id"]
        try:
            events = service.events().list(
                calendarId=cal_id,
                timeMin=time_min.isoformat(),
                timeMax=time_max.isoformat(),
                singleEvents=True,
                orderBy="startTime",
            ).execute().get("items", [])
            all_events.extend(events)
        except Exception as e:
            log.warning(f"Error leyendo calendario {cal.get('summary', cal_id)}: {e}")

    def sort_key(ev):
        return ev["start"].get("dateTime") or ev["start"].get("date")

    return sorted(all_events, key=sort_key)

def format_event(ev) -> str:
    summary = ev.get("summary", "(Sin título)")
    start = ev["start"]

    if "dateTime" in start:
        dt = datetime.fromisoformat(start["dateTime"]).astimezone(TZ)
        end_dt = datetime.fromisoformat(ev["end"]["dateTime"]).astimezone(TZ)
        return f"{dt.strftime('%H:%M')}–{end_dt.strftime('%H:%M')} {summary}"
    else:
        return f"Todo el día — {summary}"

def format_date_header(dt: datetime) -> str:
    day_name = DAYS_ES[dt.strftime("%A")]
    return f"{day_name} {dt.day} de {MONTHS_ES[dt.month]}"

def build_message(mode: str, events: list, ref_date: datetime) -> str:
    if mode == "tomorrow":
        header = f"Hola Nico\n\nTe paso las actividades de mañana, {format_date_header(ref_date)}"
    elif mode == "today":
        header = f"Hola Nico\n\nTe paso las actividades de hoy, {format_date_header(ref_date)}"
    else:
        header = f"Hola Nico\n\nActividades pendientes para hoy, {format_date_header(ref_date)}"

    if not events:
        return f"{header}\n\nNo hay actividades agendadas."

    lines = [header, ""]
    for ev in events:
        lines.append(format_event(ev))

    return "\n".join(lines)

def send_telegram(text: str):
    token = os.environ["TELEGRAM_BOT_TOKEN"]
    chat_id = os.environ["TELEGRAM_CHAT_ID"]

    url = f"https://api.telegram.org/bot{token}/sendMessage"
    resp = requests.post(
        url,
        json={"chat_id": chat_id, "text": text},
        timeout=30,
    )
    resp.raise_for_status()
    log.info("Mensaje enviado a Telegram.")

def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "today"
    now = datetime.now(TZ)

    if mode == "tomorrow":
        ref = (now + timedelta(days=1)).replace(hour=0, minute=0, second=0, microsecond=0)
        time_min = ref
        time_max = ref + timedelta(days=1)
    elif mode == "today":
        ref = now.replace(hour=0, minute=0, second=0, microsecond=0)
        time_min = ref
        time_max = ref + timedelta(days=1)
    elif mode == "pending":
        ref = now.replace(hour=0, minute=0, second=0, microsecond=0)
        time_min = now
        time_max = ref + timedelta(days=1)
    else:
        raise ValueError(f"Modo inválido: {mode}")

    service = get_calendar_service()
    events = get_events(service, time_min, time_max)
    message = build_message(mode, events, ref)
    send_telegram(message)

if __name__ == "__main__":
    main()